# Gemfile
source 'https://rubygems.org'

# git_source(:github) do |repo_name|
#   repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
#   "https://github.com/#{repo_name}.git"
# end


gem "test-unit", "~> 3.5"

gem "cucumber", "~> 8.0"
