name: Ruby Gem

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    shell: bash
    working-directory: tests
    
jobs:
  check:
    name: Check 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true 
    - run: | 
        echo 'test'
        
    - name: Code
      env:
        BUNDLE_GEMFILE: ${{ github.workspace }}//.src.gemfile
      run: |
        bundle
        bundle exec rubocop ${{ github.workspace }}/src --fail-level fatal --color
        
    - name: Tests
      env:
        BUNDLE_GEMFILE: ${{ github.workspace }}//.tests.gemfile
      run: |
        bundle
        bundle exec rubocop ${{ github.workspace }}/tests --fail-level fatal --color

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}//.tests.gemfile
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true 
    - run: |
        bundle
        bundle exec cucumber --verbose
