name: Ruby Gem

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUNDLE_GEMFILE: ${{ github.workspace }}//.tests.gemfile

defaults:
  run:
    shell: bash
    working-directory: tests
    
jobs:
  check:
    name: Check 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true 
    - run: | 
        bundle config unset deployment
        bundle add rubocop
        bundle
        
    - name: Code
      run: |
         rubocop ${{ github.workspace }}/src --fail-level fatal
        
    - name: Tests
      run: |
        rubocop ${{ github.workspace }}/tests --fail-level fatal

  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true 
    - run: |
        bundle
        bundle exec cucumber --verbose
