name: Ruby Gem

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    name: Check 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true 
    - run: |
        cd tests/
        bundle add rubocop
        bundle add parser
        bundle install 

    - name: Source
      run: |
        rubocop src
        
    - name: Tests
      run: |
        rubocop tests

  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true 
    - run: |
        cd tests/ 
        bundle  
        bundle install

    - name: Test
      run: |
        cd tests/
        bundle exec cucumber --verbose
