name: Main Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    shell: bash

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  lint:
    name: Lint 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      packages: write
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true 
    - run: | 
        bundle --quiet
        bundle exec rake lint 
        ls -faln * 
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ${{ github.workspace }}/lint.html
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2

  spec:
    name: Spec
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true 
    - run: | 
        bundle --quiet
        bundle exec rake spec

  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true 
    - run: | 
        bundle --quiet
        bundle exec rake test    
        ls -faln * coverage/
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ${{ github.workspace }}/coverage/*
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
