name: Main Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    shell: bash
    #working-directory: tests
    
jobs:
  check:
    name: Check 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true 
    - run: | 
        echo 'test'
        
    - name: Code
      env:
        BUNDLE_GEMFILE: ${{ github.workspace }}//Gemfile
      run: |
        bundle --quiet
        bundle exec rubocop ${{ github.workspace }}//src --format github --fail-level fatal --color
        
    - name: Tests
      env:
        BUNDLE_GEMFILE: ${{ github.workspace }}//Gemfile
      run: |
        bundle --quiet
        bundle exec rubocop ${{ github.workspace }}//tests --format github --fail-level fatal --color

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}//Gemfile
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true 
    - run: | 
        echo 'test'

    - name: BDD
      env:
        BUNDLE_GEMFILE: ${{ github.workspace }}//Gemfile
      run: |
        bundle --quiet
        bundle exec cucumber tests//**//*.feature --verbose 
        
    - name: TDD
      env:
        BUNDLE_GEMFILE: ${{ github.workspace }}//Gemfile
      run: |
        bundle --quiet
        ls -faln ./ ; ls -faln ./tests/ 
        # bundle exec ruby tests/*_test.rb --verbose 
        
